### ISSUE TITLE
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

### ISSUE THREAD

**Issue by sneak** [0xabad1dea/pyrtlsdr-peakfinder#1]
```
sneak@nostromo-2:~/dev$ python2 peakfinder.py 88.0 110.0
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Traceback (most recent call last):
  File "peakfinder.py", line 124, in <module>
    signals.extend(findsignals(results))
  File "peakfinder.py", line 91, in findsignals
    if candidates[1][i[0]] - prevfreq < sigdelta:
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by 0xabad1dea** [comment]
I didn't even remember I wrote this, and I don't have the hardware set up at the moment to actually run the script. Hopefully this little tweak will work:

```
# collate adjacent peaks
	for i in max:
		j = i[0] # fine, fine python wants this dereferenced now apparently
		if candidates[1][j] - prevfreq < sigdelta:
			# leans right rather than left
			# (a cool person would perfectly center it?)
			del(signals[-1])
		signals.append([i[1], candidates[1][j]])
		prevfreq = candidates[1][j]
		
	return signals
```

you can paste this directly over the "# collate adjacent peaks" part of the script. Hopefully markdown is preserving the tabs properly, or you may have to adjust them manually.

**Comment by sneak** [comment]
Strange, still didn't work, but a `j = int(i[0])` did.  `i` seems to be a numpy.ndarray and `i[0]` is a numpy.float64.  Seems to be outputting lists of frequencies now.  I might dig into it and figure out if it's working right and send you a PR to touch it up.  Thanks for the entirely unexpected tech support for a six-year old quick hack! 😄
